export const cardsData = [
  { title: "Look into render bug in dashboard", id: "1", column: "backlog" },
  { title: "Implement authentication system", id: "2", column: "backlog" },
  { title: "Design new homepage layout", id: "3", column: "todo" },
  { title: "Set up database schema", id: "4", column: "doing" },
  { title: "Fix UI bug in profile page", id: "5", column: "done" },
  { title: "Write unit tests for API", id: "6", column: "todo" },
  { title: "Deploy the app to production", id: "7", column: "doing" },
  { title: "Prepare marketing materials", id: "8", column: "done" },
  { title: "Refactor the codebase", id: "9", column: "backlog" },
  { title: "Add dark mode toggle", id: "10", column: "todo" },
  { title: "Optimize database queries", id: "11", column: "backlog" },
  { title: "Fix header bug on mobile", id: "12", column: "doing" },
  { title: "Write documentation for API endpoints", id: "13", column: "done" },
  { title: "Update product pricing page", id: "14", column: "todo" },
  { title: "Test push notifications on mobile", id: "15", column: "doing" },
  { title: "Fix payment gateway integration", id: "17", column: "done" },
  { title: "Add a feedback form", id: "18", column: "todo" },
  { title: "Setup continuous integration pipeline", id: "19", column: "doing" },
  { title: "Create a landing page for the app", id: "20", column: "backlog" },
];
